version: '3.8'

services:
  backend:
    build: ./PorfolioTracker/BackEnd
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    depends_on:
      - database

  frontend:
    build: ./cv-website/kanovsky-dev
    ports:
      - "80:80"
    depends_on:
      - backend

  database:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
